### ISSUE TITLE
Will specreduce require IRAF to be installed?

### ISSUE THREAD

**Issue by jradavenport** [crawfordsm/specreduce#1]
I see pyraf dependencies in the pyspectrograph core - will this reduction package require IRAF to run?

**Comment by crawfordsm** [comment]
Is there still pyraf dependancies in pyspectrograph?  I thought I'd remove all of them although I may have missed some.   

But no, the plan is for this to be 100% pyraf free

**Comment by jradavenport** [comment]
Excellent!

There's a few `from pyraf import iraf` lines in pyspectrograph, which is just what caught my eye

**Comment by crawfordsm** [comment]
Ah just looked at it, and it is in the stuff under identify/.   That's really just there for historical reasons, but I'll add a note to remove it 

It's actually all the stuff that I have recently ripped out of pysalt and started to make into specreduce with all the pyraf/iraf requirements removed.

So installing pyspectrograph should not requiring having pyraf installed at all.  If you run into any problems with that, let me know though and I'll make sure it is removed fully from there.
